data_mapping:
    sample_id: sample_id
    metadata.classification_label: label
    metadata.hook_left: hook_left
    metadata.setup_name: setup_name
    items.image: x
queries:
    - "sample_id < 250"
    - "metadata.classification_label in [0]"
    - 'metadata.labeling_class in ["good","bad"]'
orders:
    - "sample_id"
    - "-metadata.hook_left"
