# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from persefone.interfaces.grpc import deep_services_pb2 as persefone_dot_interfaces_dot_grpc_dot_deep__services__pb2


class DeepServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DeepServe = channel.unary_unary(
                '/persefone.DeepService/DeepServe',
                request_serializer=persefone_dot_interfaces_dot_grpc_dot_deep__services__pb2.DDeepServiceRequest.SerializeToString,
                response_deserializer=persefone_dot_interfaces_dot_grpc_dot_deep__services__pb2.DDeepServiceResponse.FromString,
                )


class DeepServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DeepServe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeepServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DeepServe': grpc.unary_unary_rpc_method_handler(
                    servicer.DeepServe,
                    request_deserializer=persefone_dot_interfaces_dot_grpc_dot_deep__services__pb2.DDeepServiceRequest.FromString,
                    response_serializer=persefone_dot_interfaces_dot_grpc_dot_deep__services__pb2.DDeepServiceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'persefone.DeepService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DeepService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DeepServe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/persefone.DeepService/DeepServe',
            persefone_dot_interfaces_dot_grpc_dot_deep__services__pb2.DDeepServiceRequest.SerializeToString,
            persefone_dot_interfaces_dot_grpc_dot_deep__services__pb2.DDeepServiceResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
