# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: persefone/interfaces/grpc/deep_services.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from persefone.interfaces.proto import comm_pb2 as persefone_dot_interfaces_dot_proto_dot_comm__pb2
from persefone.interfaces.proto import data_pb2 as persefone_dot_interfaces_dot_proto_dot_data__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='persefone/interfaces/grpc/deep_services.proto',
  package='persefone',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n-persefone/interfaces/grpc/deep_services.proto\x12\tpersefone\x1a\x1cgoogle/protobuf/struct.proto\x1a%persefone/interfaces/proto/comm.proto\x1a%persefone/interfaces/proto/data.proto\"j\n\x13\x44\x44\x65\x65pServiceRequest\x12)\n\x08metadata\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\x12(\n\x06\x62undle\x18\x02 \x01(\x0b\x32\x18.persefone.DTensorBundle\"\x96\x01\n\x14\x44\x44\x65\x65pServiceResponse\x12)\n\x06status\x18\x01 \x01(\x0b\x32\x19.persefone.ResponseStatus\x12)\n\x08metadata\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\x12(\n\x06\x62undle\x18\x03 \x01(\x0b\x32\x18.persefone.DTensorBundle2]\n\x0b\x44\x65\x65pService\x12N\n\tDeepServe\x12\x1e.persefone.DDeepServiceRequest\x1a\x1f.persefone.DDeepServiceResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,persefone_dot_interfaces_dot_proto_dot_comm__pb2.DESCRIPTOR,persefone_dot_interfaces_dot_proto_dot_data__pb2.DESCRIPTOR,])




_DDEEPSERVICEREQUEST = _descriptor.Descriptor(
  name='DDeepServiceRequest',
  full_name='persefone.DDeepServiceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='metadata', full_name='persefone.DDeepServiceRequest.metadata', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bundle', full_name='persefone.DDeepServiceRequest.bundle', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=274,
)


_DDEEPSERVICERESPONSE = _descriptor.Descriptor(
  name='DDeepServiceResponse',
  full_name='persefone.DDeepServiceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='persefone.DDeepServiceResponse.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='persefone.DDeepServiceResponse.metadata', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bundle', full_name='persefone.DDeepServiceResponse.bundle', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=277,
  serialized_end=427,
)

_DDEEPSERVICEREQUEST.fields_by_name['metadata'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_DDEEPSERVICEREQUEST.fields_by_name['bundle'].message_type = persefone_dot_interfaces_dot_proto_dot_data__pb2._DTENSORBUNDLE
_DDEEPSERVICERESPONSE.fields_by_name['status'].message_type = persefone_dot_interfaces_dot_proto_dot_comm__pb2._RESPONSESTATUS
_DDEEPSERVICERESPONSE.fields_by_name['metadata'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_DDEEPSERVICERESPONSE.fields_by_name['bundle'].message_type = persefone_dot_interfaces_dot_proto_dot_data__pb2._DTENSORBUNDLE
DESCRIPTOR.message_types_by_name['DDeepServiceRequest'] = _DDEEPSERVICEREQUEST
DESCRIPTOR.message_types_by_name['DDeepServiceResponse'] = _DDEEPSERVICERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DDeepServiceRequest = _reflection.GeneratedProtocolMessageType('DDeepServiceRequest', (_message.Message,), {
  'DESCRIPTOR' : _DDEEPSERVICEREQUEST,
  '__module__' : 'persefone.interfaces.grpc.deep_services_pb2'
  # @@protoc_insertion_point(class_scope:persefone.DDeepServiceRequest)
  })
_sym_db.RegisterMessage(DDeepServiceRequest)

DDeepServiceResponse = _reflection.GeneratedProtocolMessageType('DDeepServiceResponse', (_message.Message,), {
  'DESCRIPTOR' : _DDEEPSERVICERESPONSE,
  '__module__' : 'persefone.interfaces.grpc.deep_services_pb2'
  # @@protoc_insertion_point(class_scope:persefone.DDeepServiceResponse)
  })
_sym_db.RegisterMessage(DDeepServiceResponse)



_DEEPSERVICE = _descriptor.ServiceDescriptor(
  name='DeepService',
  full_name='persefone.DeepService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=429,
  serialized_end=522,
  methods=[
  _descriptor.MethodDescriptor(
    name='DeepServe',
    full_name='persefone.DeepService.DeepServe',
    index=0,
    containing_service=None,
    input_type=_DDEEPSERVICEREQUEST,
    output_type=_DDEEPSERVICERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DEEPSERVICE)

DESCRIPTOR.services_by_name['DeepService'] = _DEEPSERVICE

# @@protoc_insertion_point(module_scope)
