# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: persefone/interfaces/grpc/tensor_services.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from persefone.interfaces.proto import data_pb2 as persefone_dot_interfaces_dot_proto_dot_data__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='persefone/interfaces/grpc/tensor_services.proto',
  package='persefone',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n/persefone/interfaces/grpc/tensor_services.proto\x12\tpersefone\x1a%persefone/interfaces/proto/data.proto2V\n\x13SimpleTensorService\x12?\n\x07\x43onsume\x12\x18.persefone.DTensorBundle\x1a\x18.persefone.DTensorBundle\"\x00\x62\x06proto3'
  ,
  dependencies=[persefone_dot_interfaces_dot_proto_dot_data__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SIMPLETENSORSERVICE = _descriptor.ServiceDescriptor(
  name='SimpleTensorService',
  full_name='persefone.SimpleTensorService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=101,
  serialized_end=187,
  methods=[
  _descriptor.MethodDescriptor(
    name='Consume',
    full_name='persefone.SimpleTensorService.Consume',
    index=0,
    containing_service=None,
    input_type=persefone_dot_interfaces_dot_proto_dot_data__pb2._DTENSORBUNDLE,
    output_type=persefone_dot_interfaces_dot_proto_dot_data__pb2._DTENSORBUNDLE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SIMPLETENSORSERVICE)

DESCRIPTOR.services_by_name['SimpleTensorService'] = _SIMPLETENSORSERVICE

# @@protoc_insertion_point(module_scope)
