# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from persefone.interfaces.proto import data_pb2 as persefone_dot_interfaces_dot_proto_dot_data__pb2


class SimpleTensorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Consume = channel.unary_unary(
                '/persefone.SimpleTensorService/Consume',
                request_serializer=persefone_dot_interfaces_dot_proto_dot_data__pb2.DTensorBundle.SerializeToString,
                response_deserializer=persefone_dot_interfaces_dot_proto_dot_data__pb2.DTensorBundle.FromString,
                )


class SimpleTensorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Consume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimpleTensorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Consume': grpc.unary_unary_rpc_method_handler(
                    servicer.Consume,
                    request_deserializer=persefone_dot_interfaces_dot_proto_dot_data__pb2.DTensorBundle.FromString,
                    response_serializer=persefone_dot_interfaces_dot_proto_dot_data__pb2.DTensorBundle.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'persefone.SimpleTensorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SimpleTensorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Consume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/persefone.SimpleTensorService/Consume',
            persefone_dot_interfaces_dot_proto_dot_data__pb2.DTensorBundle.SerializeToString,
            persefone_dot_interfaces_dot_proto_dot_data__pb2.DTensorBundle.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
